// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424213653_UpdateMultiplePOCOs")]
    partial class UpdateMultiplePOCOs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Api.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<float?>("AudioDuration")
                        .HasColumnType("real")
                        .HasJsonPropertyName("audioDuration");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()")
                        .HasJsonPropertyName("createdAt");

                    b.Property<float?>("GuidanceScale")
                        .HasColumnType("real")
                        .HasJsonPropertyName("guidanceScale");

                    b.Property<int?>("InferStep")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("inferStep");

                    b.Property<bool>("Instrumental")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("instrumental");

                    b.Property<int>("ListenCount")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("listenCount");

                    b.Property<string>("Lyrics")
                        .HasColumnType("text")
                        .HasJsonPropertyName("lyrics");

                    b.Property<string>("LyricsDescription")
                        .HasColumnType("text")
                        .HasJsonPropertyName("lyricsDescription");

                    b.Property<string>("Prompt")
                        .HasColumnType("text")
                        .HasJsonPropertyName("prompt");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("published");

                    b.Property<string>("S3Key")
                        .HasColumnType("text")
                        .HasJsonPropertyName("r2Key");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("seed");

                    b.Property<string>("SongDescription")
                        .HasColumnType("text")
                        .HasJsonPropertyName("songDescription");

                    b.Property<string>("SongUrl")
                        .HasColumnType("text")
                        .HasJsonPropertyName("songUrl");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("status");

                    b.Property<string>("ThumbnailS3Key")
                        .HasColumnType("text")
                        .HasJsonPropertyName("thumbnailR2Key");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasJsonPropertyName("thumbnailUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Api.Models.SongCategory", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("SongId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SongCategories");

                    b.HasAnnotation("Relational:JsonPropertyName", "songCategories");
                });

            modelBuilder.Entity("Api.Models.SongLike", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("SongLikes");

                    b.HasAnnotation("Relational:JsonPropertyName", "likes");
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasAnnotation("Relational:JsonPropertyName", "user");
                });

            modelBuilder.Entity("Api.Models.Song", b =>
                {
                    b.HasOne("Api.Models.User", "User")
                        .WithMany("Songs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.SongCategory", b =>
                {
                    b.HasOne("Api.Models.Category", "Category")
                        .WithMany("SongCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Song", "Song")
                        .WithMany("SongCategories")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Api.Models.SongLike", b =>
                {
                    b.HasOne("Api.Models.Song", "Song")
                        .WithMany("Likes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.User", "User")
                        .WithMany("LikedSongs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.Category", b =>
                {
                    b.Navigation("SongCategories");
                });

            modelBuilder.Entity("Api.Models.Song", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("SongCategories");
                });

            modelBuilder.Entity("Api.Models.User", b =>
                {
                    b.Navigation("LikedSongs");

                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
