import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";

import { AuthProvider } from "@/modules/auth/providers/auth-provider";
import { TanstackQueryClientProvider } from "@/lib/query-client-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { SoundBar } from "@/modules/songs/ui/components/sound-bar";
import { AppSidebar } from "@/components/sidebar";
import Image from "next/image";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
      suppressHydrationWarning
    >
      <body className="h-screen flex flex-col">
        <ThemeProvider
          attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          <TanstackQueryClientProvider>
            <AuthProvider>
              <TooltipProvider>
                <main className="flex flex-col h-screen overflow-hidden">
                  { children }
                </main>
              </TooltipProvider>
            </AuthProvider>
          </TanstackQueryClientProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
